# Generated by Django 6.1 on 2026-08-15 09:53

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LedgerAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('account_type', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('REVENUE', 'Revenue'), ('EXPENSE', 'Expense')], max_length=20)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('idempotency_key', models.CharField(max_length=100, unique=True)),
                ('transaction_type', models.CharField(choices=[('TRANSFER', 'Transfer'), ('DEPOSIT', 'Deposit'), ('WITHDRAWAL', 'Withdrawal'), ('REFUND', 'Refund')], max_length=30)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REVERSED', 'Reversed')], default='PENDING', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('provider', models.CharField(blank=True, max_length=50)),
                ('provider_reference', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='received_transactions', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sent_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='transactions.ledgeraccount')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='transactions.transaction')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('debit__gte', 0), ('credit__gte', 0)), name='non_negative_ledger_values')],
            },
        ),
    ]
